### PR TITLE
Fix AppImage generation

### PR DESCRIPTION
**Pull request by probonopd**
Once it is correctly uploading using `provider: releases`, you can remove the line using transfer.sh.

Note that I get

```
go build -o tumblr-downloader
mv -fv tumblr-downloader tumblr-downloader-gui/
make -C tumblr-downloader-gui/ -f Makefile.meta 
mv: cannot stat ‘tumblr-downloader’: No such file or directory
make: *** [prepare-gui] Error 1
```

and the Travis CI status is red, but apparently this seems unrelated to my patch and the AppImage get generated anyway.

### CODE REVIEW

**Comment by neuro-sys** [comment]
@probonopd 

First of all, thanks for the PR!

I've just learnt that the parallelizing `-j` flag in `make -j4` breaks the build, somehow causing a race condition, and executing a rule before the previous one has finished, thus resulting in a file not found.

So if you remove `-j4` (and also one of the other `make` commands, because there are two), it should not give an error.

**Comment by probonopd** [comment]
Thanks for finding this out, build passed. Don't forget to remove the line using transfer.sh and use the GitHub Releases provider instead if you like.

**Comment by neuro-sys** [comment]
Could you please squash your commits to remove the extraneous ones? Then I can merge this, and I will modify it in a separate PR to make `deploy: releases` work.

**Comment by probonopd** [comment]
Please enable [this GitHub functionality](https://help.github.com/articles/configuring-commit-squashing-for-pull-requests/) on your repo. It allows you to squash the commits when merging.

**Pull request merged**
